// <auto-generated />
using System;
using FinancialAssetsApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinancialAssetsApp.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20251201103235_NewDBTransportd")]
    partial class NewDBTransportd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinancialAssetsApp.Models.Crypto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountCrypto")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DateAddStock")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameCrypto")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SumCrypto")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SumCryptoToRuble")
                        .HasColumnType("numeric");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Cryptos");
                });

            modelBuilder.Entity("FinancialAssetsApp.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountCurrency")
                        .HasColumnType("numeric");

                    b.Property<string>("CharCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateAddStock")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SumCurrencyToRuble")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("FinancialAssetsApp.Models.Metal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountMetal")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DateAddStock")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameMetal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SumMetals")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Metals");
                });

            modelBuilder.Entity("FinancialAssetsApp.Models.PlatformStartup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AmountCompanies")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAddStock")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NamePlatform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("SumOfStartups")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PlatformStartups");
                });

            modelBuilder.Entity("FinancialAssetsApp.Models.RealEstate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountEstate")
                        .HasColumnType("integer");

                    b.Property<string>("CityEstate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateAddStock")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SumEstate")
                        .HasColumnType("numeric");

                    b.Property<string>("TypeEstate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RealEstates");
                });

            modelBuilder.Entity("FinancialAssetsApp.Models.Startup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountStock")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAddStock")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameCompany")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NamePlatform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlatformStartupId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SumStocks")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlatformStartupId");

                    b.HasIndex("UserId");

                    b.ToTable("Startups");
                });

            modelBuilder.Entity("FinancialAssetsApp.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountStock")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAddStock")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameCompany")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SumStocks")
                        .HasColumnType("numeric");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("FinancialAssetsApp.Models.StockUSD", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountStock")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAddStock")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameCompany")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SumStocks")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SumStocksToRuble")
                        .HasColumnType("numeric");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("StocksUSD");
                });

            modelBuilder.Entity("FinancialAssetsApp.Models.Transport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAddStock")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("TypeTransport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("YearOfTransport")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Transports");
                });

            modelBuilder.Entity("FinancialAssetsApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FinancialAssetsApp.Models.Crypto", b =>
                {
                    b.HasOne("FinancialAssetsApp.Models.User", "User")
                        .WithMany("Cryptos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancialAssetsApp.Models.Currency", b =>
                {
                    b.HasOne("FinancialAssetsApp.Models.User", "User")
                        .WithMany("Currencies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancialAssetsApp.Models.Metal", b =>
                {
                    b.HasOne("FinancialAssetsApp.Models.User", "User")
                        .WithMany("Metals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancialAssetsApp.Models.PlatformStartup", b =>
                {
                    b.HasOne("FinancialAssetsApp.Models.User", "User")
                        .WithMany("PlatformStartups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancialAssetsApp.Models.RealEstate", b =>
                {
                    b.HasOne("FinancialAssetsApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancialAssetsApp.Models.Startup", b =>
                {
                    b.HasOne("FinancialAssetsApp.Models.PlatformStartup", "PlatformStartup")
                        .WithMany()
                        .HasForeignKey("PlatformStartupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinancialAssetsApp.Models.User", "User")
                        .WithMany("Startups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlatformStartup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancialAssetsApp.Models.Stock", b =>
                {
                    b.HasOne("FinancialAssetsApp.Models.User", "User")
                        .WithMany("Stocks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancialAssetsApp.Models.StockUSD", b =>
                {
                    b.HasOne("FinancialAssetsApp.Models.User", "User")
                        .WithMany("StocksUSD")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancialAssetsApp.Models.Transport", b =>
                {
                    b.HasOne("FinancialAssetsApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancialAssetsApp.Models.User", b =>
                {
                    b.Navigation("Cryptos");

                    b.Navigation("Currencies");

                    b.Navigation("Metals");

                    b.Navigation("PlatformStartups");

                    b.Navigation("Startups");

                    b.Navigation("Stocks");

                    b.Navigation("StocksUSD");
                });
#pragma warning restore 612, 618
        }
    }
}
